# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'mgazurepipelineproject-conn'
    subscriptionId: '9a8c9905-bebf-4798-beab-08b0dea82d91'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'mgazurepipelineproject'
    location: 'Central US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/architectincloud/mgazurepipelineproject/master/CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName mgazurepipelineproject'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'